version: '3.8'

services:
  tailadmin-app:
    image: ${DOCKER_USER}-tailadmin-laravel:beta
    container_name: tailadmin-laravel-app
    ports:
      - "8090:8000"
    environment:
      - DB_HOST=tailadmin-mysql
      - DB_DATABASE=social_media
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    depends_on:
      - tailadmin-mysql
    networks:
      - tailadmin-network
    restart: unless-stopped

  tailadmin-mysql:
    image: mysql:5.7
    container_name: tailadmin-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=social_media
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    volumes:
      - tailadmin_mysql_data:/var/lib/mysql
    networks:
      - tailadmin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tailadmin-network:
    driver: bridge

volumes:
  tailadmin_mysql_data:
    driver: local
